apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: python-template-app
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: python-template
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://shockedshodan.github.io/template-python-test/charts-repo/
    chart: app
    targetRevision: 0.1.0-dev.0.main.1f54c310
  syncPolicy:
    automated: 
     prune: true 
     selfHeal: true 
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true